name: ci

on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8 pylint pytest black
          pip install -r requirements.txt
      - name: Lint with flake8
        run: |
          # stop the build if there are Python syntax errors or undefined names
          flake8 primelooter.py --count --show-source --statistics
      - name: Lint with pylint
        run: |
          pylint primelooter.py --fail-under 10 --disable=all --enable=classes --disable=W
      - name: Lint with black
        run: |
          black primelooter.py --check
